### PR TITLE
Gas optimized and currentTime function added

### LINKED ISSUE #29: Require gas optimization in CrowdFunding smart contract
### Is your feature request related to a problem? Please describe.
Current contract for CrowdFunding is gas expensive. It requires some optimization.

### Additional context
Add a function to check current time stamp for checking and updating the deadline for registrations accordingly.

### PR DESCRIPTION
**Pull request by RijuChakraborty**
## Fixes #29 
Gas optimized the CrowdFunding contract. The changes helped to reduce gas costs by ~50k units.
Added a current time function to check and update the deadline for each registrations accordingly.
Also removed "amountRaised=0"  in constructor as solidity by default initializes uint variables with 0.
@0xVikasRushi  please have a look.

### CODE REVIEW

**Comment by 0xVikasRushi** [comment]
Yeah ! @RijuChakraborty

**Review by advaita-saha — APPROVED** [review]
Great work @RijuChakraborty

**Comment by advaita-saha** [comment]
@RijuChakraborty 
Please create a issue regarding the problem you solved

It helps us keep a track of everything

**Comment by RijuChakraborty** [comment]
> @RijuChakraborty Please create a issue regarding the problem you solved
> 
> It helps us keep a track of everything

Yeah sure 👍

**Pull request merged**
