### PR TITLE
Add ERC1155 token contract

### LINKED ISSUE #5: ERC-1155 NFT contract
### Is your feature request related to a problem? Please describe
Create a ERC-1155 standard NFT

### Describe the solution you'd like
create a file inside `contract/NFT/<your_filename.sol>`
Implement the standard logic, and feel free to add your customisation, without violating the standards.

### PR DESCRIPTION
**Pull request by adityabhattad2021**
## Description
Closes #5 
_Give a summary of the change that you have made_ <br />
Added ERC1155 NFT contract

Fixes #[ISSUENO]

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by advaita-saha** [comment]
@adityabhattad2021 
Good work
Please comment your code a bit

**Comment by adityabhattad2021** [comment]
What should I comment?

**Comment by advaita-saha** [comment]
great work
Don't forget to follow the steps mentioned in here
https://github.com/metafy-social/web3-smart-contracts/pull/17#issuecomment-1264212996

**Comment by advaita-saha** [comment]
LGTM

**Pull request merged**
