### PR TITLE
added faucet contract file

### LINKED ISSUE #13: Create a Faucet smart contract
### Describe the solution you'd like
I want to create a faucet smart contract for a specific ERC20 token where anybody will be able to get a certain amount of token from the contract's account to there account.

### PR DESCRIPTION
**Pull request by nirban256**
## Description

I have added a faucet smart contract under the Misc folder which shows the implementation of the faucet contract.

Fixes #13 

## Screenshots of relevant screens

Screenshot (21)

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by nirban256** [comment]
@advaita-saha pls review it once

**Review by advaita-saha — APPROVED** [review]

**Comment by advaita-saha** [comment]
LGTM

Don't forget to follow the aforesaid steps to be eligible for rewards
https://github.com/metafy-social/web3-smart-contracts/pull/23#issuecomment-1264458903

**Comment by nirban256** [comment]
thanks and I have already linked my discord and github account and provided my metamask address, and registered myself to be eligible. Is this all? @advaita-saha

**Comment by advaita-saha** [comment]
> thanks and I have already linked my discord and github account and provided my metamask address, and registered myself to be eligible. Is this all? @advaita-saha

Yess
Best of luck for Hacktoberfest

**Comment by nirban256** [comment]
> > thanks and I have already linked my discord and github account and provided my metamask address, and registered myself to be eligible. Is this all? @advaita-saha
> 
> Yess Best of luck for Hacktoberfest

thanks

**Pull request merged**
